=== mantoine2013/ConjugAram/ConjugSyri.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    	<xs:element name="lexique" type="CTlexique"/>
        
        
	<xs:complexType name="CTlexique">
            <xs:sequence maxOccurs="unbounded">
		<xs:element name="entrée" type="CTentrée"/>
            </xs:sequence>                
        </xs:complexType>

        <xs:complexType name="CTentrée">
            <xs:choice maxOccurs="unbounded">
		<xs:element name="usage" type="CTsource"/>
            </xs:choice>
            <xs:attribute name="racine" type="xs:ID" use="required"/>
	</xs:complexType>

        <xs:complexType name="CTr">
            <xs:simpleContent>
		<xs:extension base="xs:string">
		</xs:extension>
            </xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="CTsource" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="verbe" type="CTr"/>
			<xs:element name="note" type="xs:string"/>
			<xs:element name="def" type="xs:string"/>
		</xs:choice>
	</xs:complexType>


</xs:schema>

=== mantoine2013/ConjugAram/ConjugSyri.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexique
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='ConjugSyri.xsd'>


    <entrée racine="ܐܙܠ"><verbe infinitif="ܐܙܠ"><usage>aller</usage></verbe></entrée>
    <entrée racine="ܫܒܩ">
        <verbe infinitif="ܫܒܩ">
        <usage>remettre</usage>
        </verbe>
    </entrée>
    <entrée racine="ܥܠ">
        <verbe infinitif="ܥܠ">
        <usage>aller</usage>
        </verbe>
    </entrée>
    <entrée racine="ܥܪܩ">
        <verbe infinitif="ܥܪܩ">
        <usage>fuir</usage>
        </verbe>
    </entrée>
    <entrée racine="ܕܒܪ">
        <verbe infinitif="ܕܒܪ">
        <usage>conduire</usage>
        </verbe>
    </entrée>
    <entrée racine="ܟܘܢ">
        <verbe infinitif="ܟܘܢ">
        <usage>exister/être</usage>
        </verbe>
    </entrée>
    <entrée racine="ܫܡܥ">
        <verbe infinitif="ܫܡܥ">
        <usage>écouter</usage>
        </verbe>
    </entrée>
    <entrée racine="ܦܢܳܐ">
        <verbe infinitif="ܦܢܳܐ">
        <usage>tourner</usage>
        <usage>se convertir</usage>
        </verbe>
    </entrée>

    <entrée racine="ܡܪܳܐ">
        <verbe infinitif="ܡܪܳܐ">
        </verbe>
        <usage>parler</usage>
    </entrée>
        <entrée racine="ܩܛܰܠ">
        <verbe infinitif="ܩܛܰܠ">
        </verbe>
        <usage>parler</usage>
    </entrée>

</lexique>
